import type { Metadata } from "next";
import Header from "@/widgets/layout/header";
import "./index.css";


export const metadata: Metadata = {
  title: "AI-School by Grafov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="container px-[64px] pt-[20px]"
      >
      <Header />
      <video className="w-full h-[1000px]" autoPlay={true} playsInline={true} loop={true} muted={true} src={"video/video.mp4"}></video>
        {children}
      </body>
    </html>
  );
}
