import type { Metadata } from "next"
import Header from "@/widgets/layout/header"
import "./index.css"

export const metadata: Metadata = {
  title: "AI-School by Grafov",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="container px-[58px] pt-[20px]">
        <Header />
        {children}
      </body>
    </html>
  )
}
